### ISSUE TITLE
'spevktator' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by GreenAA** [MischaU8/spevktator#4]
spevktator>spevktator --help
'spevktator' is not recognized as an internal or external command,
operable program or batch file.

**Comment by GreenAA** [comment]
![Screenshot 2024-03-18 164013](https://github.com/MischaU8/spevktator/assets/87846163/592a0abb-5ce9-4a11-8dad-56d154b89aa9)

bro i try with all py . 9.1, 11.7 . 12.2. , 13.1

cant install the pip install .

you can help ?

**Comment by GreenAA** [comment]
with py 12 is work but get anither error 

`  error: subprocess-exited-with-error
  Created wheel for spevktator: filename=spevktator-0.1.0-py3-none-any.whl size=20528 sha256=91b6e24acd266b967
  × python setup.py bdist_wheel did not run successfully.                                                    ionWarning: Invalid dash-separated options
      !! code: 1
  ╰─> [81 lines of output]
              ********************************************************************************uptoolsDeprecati
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\fasttext
      copying python\fasttext_module\fasttext\FastText.py -> build\lib.win32-cpython-311\fasttext
      copying python\fasttext_module\fasttext\__init__.py -> build\lib.win32-cpython-311\fasttext
      creating build\lib.win32-cpython-311\fasttext\util
      copying python\fasttext_module\fasttext\util\util.py -> build\lib.win32-cpython-311\fasttext\util      stsxt\tests
      copying python\fasttext_module\fasttext\tests\__init__.py -> build\lib.win32-cpython-311\fasttext\tests
      running build_extb.win32-cpython-311\fasttext\tests
      building 'fasttext_pybind' extensionext\tests\test_configurations.py -> build\lib.win32-cpython-311\fast
      creating build\temp.win32-cpython-311
      creating build\temp.win32-cpython-311\Release
      creating build\temp.win32-cpython-311\Release\python
      creating build\temp.win32-cpython-311\Release\python\fasttext_module
      creating build\temp.win32-cpython-311\Release\python\fasttext_module\fasttext                          19\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.3351
      [end of output]
      C:\Users\eyal\AppData\Local\Temp\pip-install-4d75rmzx\fasttext_97d045574f9445a68b8a15bb75e8e80e\src\dens
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
Successfully built spevktator
Failed to build fasttext
ERROR: Could not build wheels for fasttext, which is required to install pyproject.toml-based projects`

**Comment by GreenAA** [comment]
don't answer here  ?

**Comment by MischaU8** [comment]
Sorry, I don't have experience with installing python packages on Windows. It appears that the dependency `fasttext` isn't supported.

**Comment by GreenAA** [comment]
with python 12 is working ,, but the new error is 
`Failed to build fasttext
ERROR: Could not build wheels for fasttext, which is required to install pyproject.toml-based projects``

**Comment by GreenAA** [comment]
i tell u what the problem  . .. 
`**i install git clone >> cd spevaktator > wget pack > pip install datasette > datasette** 
`
now is ok , working 

with pyhon 3,12

**Comment by GreenAA** [comment]
u need remove 

`**pip3 install .**`

datasette `**data/**` only datasette

thanks

**Comment by GreenAA** [comment]
no still problem .. only the server workking , with the word Spevktator not working  .

**Comment by GreenAA** [comment]
mischa qustion pls 

when i run the  datasette data/

`Traceback (most recent call last):
  File "c:\users\777da\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\777da\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\777da\AppData\Local\Programs\Python\Python38\Scripts\datasette.exe\__main__.py", line 9, in <module>
    sys.exit(cli())
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\datasette\cli.py", line 578, in serve
    ds = Datasette(files, **kwargs)
  File "c:\users\777da\appdata\local\programs\python\python38\lib\site-packages\datasette\app.py", line 261, in __init__
    metadata = parse_metadata(fp.read())
  File "c:\users\777da\appdata\local\programs\python\python38\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5078: character maps to <undefined>
PS C:\PycharmP\spevktator> `

**UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5078: character maps to** 


how i can fix it  ?

**Comment by GreenAA** [comment]
MischaU8 any help here ?

**Comment by MischaU8** [comment]
That looks like an Unicode decoding issue when loading the metadata in datasette. Have you changed that configuration file?

Maybe you can find the issue upstream: https://github.com/simonw/datasette

**Comment by GreenAA** [comment]
hi no any changes  , , 

i install step by spet ...

**Comment by GreenAA** [comment]
but i remove from my pc .. thanks ... a lot problem , minimum support  . 

but thanks you upload the spevaktator ..
